### ISSUE TITLE
Support new `host` parameter similar to snowflake provider

### ISSUE THREAD

**Issue by michael-robbins** [aidanmelen/terraform-provider-snowsql#21]
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/provider/provider.go#L134 has recently introduced a `host` parameter so we don't have to hack around with the `region` including extra domains like `.privatelink` for example.

It would be good if we could do that here too so our snowflake providers all have similar args/experience!

**Comment by aidanmelen** [comment]
don't blink

**Comment by aidanmelen** [comment]
https://registry.terraform.io/providers/aidanmelen/snowsql/0.4.2

**Comment by michael-robbins** [comment]
Thanks for the speedy service! :D
