### ISSUE TITLE
Terraform provider changed

### ISSUE THREAD

**Issue by Pavel-Millstein** [aidanmelen/terraform-provider-snowsql#33]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.2.1

### Affected Resource(s)
-snowsql_exec

### Terraform provider path for snowflake changed from:
github.com/chanzuckerberg/terraform-provider-snowflake
to:
github.com/Snowflake-Labs/terraform-provider-snowflake

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by michael-robbins** [comment]
Yeah this is breaking our setup as well, you'd have thought they would have duplicated it and not 'moved' it 😭

**Comment by tekumara** [comment]
As a workaround for now, pinning to [chanzuckerberg/snowflake 0.33.1](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.33.1) (the last release under the old name) should work.

**Comment by aidanmelen** [comment]
This is the error I am getting on `terraform init` with the snowflake provider on version 0.34.0

```
╷
│ Warning: Additional provider information from registry
│ 
│ The remote registry returned warnings for registry.terraform.io/chanzuckerberg/snowflake:
│ - For users on Terraform 0.13 or greater, this provider has moved to Snowflake-Labs/snowflake. Please update your source in required_providers.
╵

╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/chanzuckerberg/snowflake v0.34.0 does not have a package available for your current platform, darwin_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different
│ platforms supported.
```

It looks like they migrated the project to a different owner.

**Comment by aidanmelen** [comment]
The solution I found was to specify the new snowflake provider in the `provider.tf` file. Please see the update [example/simple/provider.tf](https://github.com/aidanmelen/terraform-provider-snowsql/blob/main/examples/simple/provider.tf#L6) for more information

**Comment by tekumara** [comment]
FYI - to upgrade to the new provider you'll need to also update your state file manually and rename `chanzuckerberg` -> `snowflake-labs`
