### ISSUE TITLE
No active warehouse selected in the current session

### ISSUE THREAD

**Issue by jrobison-sb** [aidanmelen/terraform-provider-snowsql#35]
### Terraform Version
```
$ terraform -v
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/aidanmelen/snowsql v0.4.3
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.36
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `snowsql_exec`

### Terraform Configuration Files
```
terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.36"
    }
    snowsql = {
      source  = "aidanmelen/snowsql"
      version = "0.4.3"
    }
  }
}

provider "snowflake" {
  # See https://guides.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#2
  # for instructions on how to set up a user account to be used by Terraform.
  // required
  username = "automation"
  account  = "REDACTED"
  # password is exposed as an environment variable
  region = "us-east-1"

  // optional
  role = "ACCOUNTADMIN"
}

provider "snowsql" {
  # See https://guides.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#2
  # for instructions on how to set up a user account to be used by Terraform.
  // required
  username = "automation"
  account  = "REDACTED"
  # password is exposed as an environment variable
  region = "us-east-1"

  // optional
  role = "ACCOUNTADMIN"
}

resource "snowflake_warehouse" "foo" {
  name           = "FOO"
  comment        = "FOO"
  warehouse_size = "small"
}

resource "snowflake_user" "foo" {
  name                 = "FOO"
  login_name           = "FOO"
  disabled             = false
  display_name         = "FOO"
  email                = "foo@example.com"
  must_change_password = false
}

resource "snowsql_exec" "monitor" {
  name = "SANDBOX3-SFMONTOR"

  create {
    statements = <<-EOT
    USE WAREHOUSE "${snowflake_warehouse.foo.name}";

    CREATE OR REPLACE RESOURCE MONITOR "SANDBOX3-SFMONITOR" WITH
      CREDIT_QUOTA = 50
      FREQUENCY = DAILY
      START_TIMESTAMP = IMMEDIATELY
      NOTIFY_USERS = ( ${join(", ", [
    snowflake_user.foo.name,
])} )
      TRIGGERS ON 100 PERCENT DO SUSPEND;

    ALTER ACCOUNT SET RESOURCE_MONITOR = "SANDBOX3-SFMONITOR";
  EOT
}

delete {
  statements = <<-EOT
    ALTER ACCOUNT UNSET RESOURCE_MONITOR;
    DROP RESOURCE MONITOR "SANDBOX3-SFMONITOR";
  EOT
}
}
```

### Expected Behavior
Terraform should executed the expected `USE WAREHOUSE` statement and then the expected `CREATE OR REPLACE RESOURCE MONITOR` statement.

### Actual Behavior

```
snowsql_exec.monitor: Creating...
╷
│ Error: 000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
│ 
│ 
│   with snowsql_exec.monitor,
│   on main.tf line 55, in resource "snowsql_exec" "monitor":
│   55: resource "snowsql_exec" "monitor" {
```

### Steps to Reproduce
Paste the above HCL into a terraform file, and then:
1. `terraform init`
2. `terraform apply`

### Important Factoids
The desired `USE WAREHOUSE` and `CREATE OR REPLACE RESOURCE MONITOR` statements run fine if I paste them into a worksheet in the console and run them there, using the same credentials/role as terraform uses.

I'll also add that I'm aware of the `snowflake_resource_monitor` resource in the snowflake provider, and I would prefer to use that instead of using `snowsql_exec`, but `snowflake_resource_monitor` doesn't currently support `NOTIFY_USERS`, so that's how I ended up with `snowsql_exec`.

**Comment by aidanmelen** [comment]
Duplicates #16

**Comment by aidanmelen** [comment]
> It is possible the use warehouse command is not supported by multi statement exec via underlying Go library.

It looks like you can loop through the multiple statements and return the results sequentially. That might do it. Feel free to make a PR! I may get to this eventually but is low priority for me at this time. For this reason, I would utilize multiple providers to get the functionality you want today. My apologies as the multi provider solution is not optimal.
