### ISSUE TITLE
[feature-request] add a changelog?

### ISSUE THREAD

**Issue by jrobison-sb** [aidanmelen/terraform-provider-snowsql#37]
(I'll mention my own use case with dependabot, but the same thing applies in a less automated fashion even when humans are doing an upgrade...).

We use dependabot to keep our provider version pins updated, and it helpfully displays a changelog whenever it proposes an upgrade. The trouble is that this repo apparently doesn't use a changelog, so dependabot has no source of truth for what is going to change:
<img width="438" alt="Screen Shot 2022-06-29 at 3 26 19 PM" src="https://user-images.githubusercontent.com/39737211/176519610-5faebc79-9d39-4f09-b4d8-8051b4d9d513.png">

It only becomes apparent to the user that there is a breaking change between these two versions when they run a `plan` and the plan breaks:
<img width="445" alt="Screen Shot 2022-06-29 at 3 27 09 PM" src="https://user-images.githubusercontent.com/39737211/176519875-06e7b6bb-2d45-4970-a870-8180df293765.png">

It would be more user-friendly if the breaking change (and really, any change) was called out in a changelog. Would it be possible to add one?.

I'll add that I'm not opposed to looking around at other OSS projects and see how they handle it, and then see what I can paste into GitHub actions to get it working and make a PR here to contribute it, if that would be welcomed.

Thanks.

**Comment by aidanmelen** [comment]
Thanks for calling this out. I will retroactively go update the changelog for releases.

**Comment by jrobison-sb** [comment]
Coincidentally, I think I was the one who raised the issue which eventually lead to the deletion of `delete_on_create`, so I'm personally already mostly aware of this change. My request here is more about "a changelog is a good thing to have in general, and on an ongoing basis", rather than any question about this individual breaking change from #15.

Thanks.

**Comment by aidanmelen** [comment]
I really like Github Releases to track changes. I just found out there is an auto-generate release notes based of PRs and commit messages. It is pretty slick.

<img width="1160" alt="Screen Shot 2022-08-08 at 8 05 26 PM" src="https://user-images.githubusercontent.com/7491003/183547746-8431ac3a-3e96-4555-a1a2-15d54250edc9.png">

**Comment by jrobison-sb** [comment]
Works great, thank you!
<img width="548" alt="Screen Shot 2022-08-09 at 9 25 40 AM" src="https://user-images.githubusercontent.com/39737211/183658354-ac384c8c-73a0-47b2-83a0-3bc455c3e8cd.png">
