### ISSUE TITLE
Warehouse declaration not supported in snowsql provider 

### ISSUE THREAD

**Issue by mightyatom** [aidanmelen/terraform-provider-snowsql#44]
Hi @aidanmelen ,

I am encountering an issue when having multiple grant statements (more than one) defined in either the `create` or `delete` lifecycle. Given such a configuration the `terraform apply` always errors out complaining about no active warehouse selected. When attempting with the warehouse attribute in the snowsql provider configuration, an error is given stating the warehouse is not a supported argument.

### Terraform Version
Terraform v1.0.11

### Affected Resource(s)
- snowsql_exec

### Terraform Configuration Files
```hcl
provider "snowsql" {
  account          = var.account
  region           = var.region
  username         = var.snowsql_username
  private_key_path = var.private_key_path

  warehouse = "compute_wh"
}

resource "snowsql_exec" "snowsql_exec_test" {
  name = "snowsql_exec_test"

  create {
    statements = <<-EOT
    grant select on view CITIBIKE.PUBLIC.TRIPS_V to role ${snowflake_role.role.name};
    grant select on view CITIBIKE.PUBLIC.TRIPS_V to role ${snowflake_role.role.name};
    EOT
  }

  delete {
    statements = <<-EOT
    revoke select on view CITIBIKE.PUBLIC.TRIPS_V from role ${snowflake_role.role.name};
    revoke select on view CITIBIKE.PUBLIC.TRIPS_V from role ${snowflake_role.role.name};
    EOT
  }

}
```

### Expected Behavior
What should have happened?
- An active warehouse is not required while executing grant statements
- The attribute `warehouse` should be supported in the snowsql provider configuration similar to the snowflake provider. [This](https://github.com/aidanmelen/terraform-provider-snowsql/blob/086710f97c13fd345c31686e64326f6f4536044e/snowsql/provider.go#L121) line of code indicates it should have been a valid argument. 

### Actual Behavior
What actually happened?
- An error popped up when multiple grant statements are declared 
```
Error: 000606 (57P03): No active warehouse selected in the current session.  
Select an active warehouse with the 'use warehouse' command.
│ 
│ 
│   with snowsql_exec.snowsql_exec_test,
│   on test.tf line 67, in resource "snowsql_exec" "snowsql_exec_test":
│   67: resource "snowsql_exec" "snowsql_exec_test" {
```
- An error popped up when attempting to declare warehouse in the snowsql provider
```
Error: Unsupported argument
│ 
│   on main.tf line 30, in provider "snowsql":
│   30:   warehouse = "compute_wh"
│ 
│ An argument named "warehouse" is not expected here.
```

**Comment by hzhang-wesdigital** [comment]
hi @aidanmelen  
I just came across this PR #42 and hence cloned the repo and built/installed the snowsql provider locally for testing. Unfortunately, it is still not able to recognise the `warehouse` argument. 

- Built and installed locally
```shell
$ make install
go build -o terraform-provider-snowsql
mkdir -p ~/.terraform.d/plugins/registry.example.io/local/snowsql/0.4.4/darwin_amd64
mv terraform-provider-snowsql ~/.terraform.d/plugins/registry.example.io/local/snowsql/0.4.4/darwin_amd64
```

- Modified my main.tf
```hcl
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.35"
    }
    snowsql = {
      source  = "registry.example.io/local/snowsql"
      version = "= 0.4.4"
    }
  }
}

provider "snowsql" {
  account          = var.account
  region           = var.region
  username         = var.snowsql_username
  private_key_path = var.private_key_path

  warehouse = "compute_wh"
}
```
- Executed `terraform init` 
```shell
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding snowflake-labs/snowflake versions matching "~> 0.35"...
- Finding registry.example.io/local/snowsql versions matching "0.4.4"...
- Finding latest version of hashicorp/tls...
- Installing snowflake-labs/snowflake v0.40.0...
- Installed snowflake-labs/snowflake v0.40.0 (signed by a HashiCorp partner, key ID 5166D7352E69A585)
- Installing registry.example.io/local/snowsql v0.4.4...
- Installed registry.example.io/local/snowsql v0.4.4 (unauthenticated)
- Installing hashicorp/tls v4.0.1...
- Installed hashicorp/tls v4.0.1 (signed by HashiCorp)
```
- Ran `terraform plan` given the same error
```shell
$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 30, in provider "snowsql":
│   30:   warehouse = "compute_wh"
│ 
│ An argument named "warehouse" is not expected here.
```

**Comment by aidanmelen** [comment]
thanks for reporting the issue! I will look into this issue. In the meantime, there is a work around described [here](https://github.com/aidanmelen/terraform-provider-snowsql/issues/16#issuecomment-1065735556).

Essentially, it means setting the `DEFAULT_WAREHOUSE` on the user that the `snowsql` provider is used to authenticate. I realize that is not ideal for users of this provider which is why I would like to fix this issue.

**Comment by aidanmelen** [comment]
it also looks like there is a second work around described [here](https://github.com/aidanmelen/terraform-provider-snowsql/issues/16#issuecomment-1065754407).

still I will look into fixing this issue

**Comment by aidanmelen** [comment]
another option is to use the environment variable.

`SNOWFLAKE WAREHOUSE='COMPUTE WH'`

**Comment by aidanmelen** [comment]
please use the upcoming v1.0.0 release to use the `provider.warehouse` feature.

**Comment by mightyatom** [comment]
thank you @aidanmelen just did a `terraform init -upgrade` and everything works as expected on my end!
