### ISSUE TITLE
snow_exec gives error on multiple statement

### ISSUE THREAD

**Issue by almekpoh** [aidanmelen/terraform-provider-snowsql#92]
Hi, 

I keep having this error from time to time, even though I have privilege on this schema and only have 2 statements.
What's is weird is that when I retry without changing anything, it works.

Statements:
GRANT INSERT ON ALL TABLES IN SCHEMA DATABASE.TEST TO ROLE USER_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DATABASE.TEST  TO ROLE USER_ROLE;

100132 (P0000): JavaScript execution error: Uncaught Execution of multiple statements failed on statement "GRANT INSERT ON FUTURE TABLES ..." (at line 2, position 0).
SQL access control error:
Insufficient privileges to operate on schema 'TEST' in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace:
SYSTEM$MULTISTMT line: 10

Do you have any clue of what is going on ?
i didn't have this type of error on version 1.1.0, I  have just migrated !

**Comment by aidanmelen** [comment]
The error seems to suggest that the snowsql provider does not have the correct privileges:

> Insufficient privileges to operate on schema 'TEST' in SYSTEM

Please ensure the user or role passed to the snowsql provider has the correct privileges or ownership on the TEST schema.

**Comment by aidanmelen** [comment]
Interesting that the gosnowflake library would be returning a permission error.

Three things to try:

1. first ensure this command works in a snowflake worksheet with the same privileges.
2. try breaking this up in to multiple statements with a single command to see if it still fails. This will help determine if this is an issue either ExecContext with multiple statements or not.
3. Fully qualify the statements if you haven't already.

**Comment by aidanmelen** [comment]
This works:

**Comment by aidanmelen** [comment]
I was able to reproduce the error:

```
╷
│ Error: failed to execute create statements.
│ 
│ Statements:
│ 
│   GRANT INSERT ON ALL TABLES IN SCHEMA DATABASE.TEST TO ROLE USER_ROLE;
│ GRANT INSERT ON FUTURE TABLES IN SCHEMA DATABASE.TEST TO ROLE USER_ROLE;
│ 
│ 
│ 100132 (P0000): JavaScript execution error: Uncaught Execution of multiple statements failed on statement "GRANT INSERT ON ALL TABLES IN ..." (at line 1, position 0).
│ SQL compilation error:
│ Database 'DATABASE' does not exist or not authorized. in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
│ stackstrace: 
│ SYSTEM$MULTISTMT line: 10
│ 
│   with snowsql_exec.role_grant_all,
│   on main.tf line 28, in resource "snowsql_exec" "role_grant_all":
│   28: resource "snowsql_exec" "role_grant_all" {
│ 
```

when I provided a statement that referenced a database that either does not exist or I do not have access to (in this case, the database did not exist). Please see the terraform code below that was used to reproduced the error for further insights:

```terraform
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = ">= 0.56.5"
    }
    snowsql = {
      source  = "aidanmelen/snowsql"
      version = ">= 1.3.3"
    }
    random = ">= 2.1"
  }
}

provider "snowflake" {}
provider "snowsql" {}

resource "snowflake_database" "database" {
  name = "TEST"
}

resource "snowflake_role" "role" {
  name = "USER_ROLE"
}

resource "snowsql_exec" "role_grant_all" {
  name = "TERRAFORM_PROVIDER_SNOWSQL_ISSUE_92"

  create {
    statements           = <<-EOT
      GRANT INSERT ON ALL TABLES IN SCHEMA DATABASE.${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
      GRANT INSERT ON FUTURE TABLES IN SCHEMA DATABASE.${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
    EOT
    # number_of_statements = 2
  }

  read {
    statements           = <<-EOT
      SHOW GRANTS TO ROLE ${snowflake_role.role.name};
      SHOW FUTURE GRANTS TO ROLE ${snowflake_role.role.name};
    EOT
    number_of_statements = 2
  }

  delete {
    statements           = <<-EOT
      REVOKE INSERT ON ALL TABLES IN SCHEMA DATABASE.${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
      REVOKE INSERT ON FUTURE TABLES IN SCHEMA DATABASE.${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
    EOT
    # number_of_statements = 2
  }
}

output "show_role_grant_all_results" {
  description = "The SnowSQL query results from the read statements."
  value       = jsondecode(nonsensitive(snowsql_exec.role_grant_all.read_results))
}
```

**Comment by aidanmelen** [comment]
Please reach out if you have any other questions.

**Comment by almekpoh** [comment]
Oh okay, I will check one more time database access privileges in this case, it might be in my dependencies.
thank you

**Comment by aidanmelen** [comment]
Please let me know if that resolved your issue. Thanks

**Comment by almekpoh** [comment]
Hi @aidanmelen , it seems that it works, it haven't encounter this error again for now.

**Comment by aidanmelen** [comment]
Also, it should be noted that the snowflake provider now offers, as of recent, support for [grant all on schema](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1686).

**Comment by almekpoh** [comment]
thanks for letting me now this. I will keep an eye on this as well.
