### ISSUE TITLE
subsequent tf plan and apply dont work

### ISSUE THREAD

**Issue by vijayrgopu** [aidanmelen/terraform-provider-snowsql#98]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.5.0

### Affected Resource(s)
"snowsql_exec"

I am using this to insert configuration into specific snowflake tables which works for the first time but subsequent terraform plan and apply commands fail complaining about "Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name."

in my commands i have provided what database to use and what schema to use using the commands USE DATABASE etc. however it doesnt recognize these values and fails.

provider "snowsql" {
  username  = 
  account   = 
  password  = 
  warehouse = 
  role      = 
}

resource "snowsql_exec" "insert_shard_config" {
  create {
    statements = <<-EOT
        USE DATABASE ${snowflake_database.database.name};
        USE SCHEMA ${snowflake_schema.schema.name};
        INSERT INTO XYZ.ABC_TBL (COL) VALUES ('COL1');
    EOT
  }
  read {
    statements = <<-EOSTMT
        USE DATABASE ${snowflake_database.database.name};
        USE SCHEMA ${snowflake_schema.schema.name};
        SELECT COUNT(*) FROM XYZ.ABC_TBL;
    EOSTMT
  }
  delete {
    statements = <<-EOD
        USE DATABASE ${snowflake_database.database.name};
        USE SCHEMA ${snowflake_schema.schema.name};
        DELETE FROM XYZ.ABC_TBL WHERE 1=2;
    EOD
  }
  depends_on = [
        snowflake_table.table_config
  ]
}

**Comment by aidanmelen** [comment]
Thanks for opening an issue. I will need to investigate further, but i suspect the USE statements are causing the problems. Have you tried full qualifying the SELECT statement?

In the meantime, you can also try to remove the `read` block as it is optional for the resource.

**Comment by aidanmelen** [comment]
The `read.statements` from the `snowsql_exec` resource share the same query logic as `snowsql_query` data resource. Multiple query statements are supported by this provider, but they must be fully qualified. For example:

```terraform
# multi-statement queries
data "snowsql_query" "count_snowflake_sample_data_tables" {
  statements = <<-EOT
    select 'customer' AS table_name, count(*) as count from snowflake_sample_data.tpch_sf1.customer;
    select 'lineitem' AS table_name, count(*) as count from snowflake_sample_data.tpch_sf1.lineitem;
    select 'nation' AS table_name, count(*) as count from snowflake_sample_data.tpch_sf1.nation;
  EOT
}
```

The create, update, and delete statements support multiple `USE` because they ignore the rows returned.
